version: "3.8"

services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
  #   container_name: elasticsearch7
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - bootstrap.memory_lock=true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata7:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    container_name: kibana7
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  esdata7:

networks:
  elastic:
    driver: bridge
